# Классическое машинное обучение
### NumPy и почему это быстро. Векторизация операций.

## Библиотека NumPy

In [1]:
import numpy as np

## Массив `numpy.array`

![list-array.png](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/list-array.png)

### Простейшие функции на массиве

#### Задача 1

NumPy реализует множество функций, которые могут быть применены к каждому элементу в массиве **без использования циклов**.

Реализуйте функции, которые работают таким образом:
1. ReLU
2. ReLU6
3. SoftPlus

Какие могут быть проблемы при реализации последней функции?

In [2]:
a = np.linspace(-10, 10, 1000)
a

array([-10.        ,  -9.97997998,  -9.95995996,  -9.93993994,
        -9.91991992,  -9.8998999 ,  -9.87987988,  -9.85985986,
        -9.83983984,  -9.81981982,  -9.7997998 ,  -9.77977978,
        -9.75975976,  -9.73973974,  -9.71971972,  -9.6996997 ,
        -9.67967968,  -9.65965966,  -9.63963964,  -9.61961962,
        -9.5995996 ,  -9.57957958,  -9.55955956,  -9.53953954,
        -9.51951952,  -9.4994995 ,  -9.47947948,  -9.45945946,
        -9.43943944,  -9.41941942,  -9.3993994 ,  -9.37937938,
        -9.35935936,  -9.33933934,  -9.31931932,  -9.2992993 ,
        -9.27927928,  -9.25925926,  -9.23923924,  -9.21921922,
        -9.1991992 ,  -9.17917918,  -9.15915916,  -9.13913914,
        -9.11911912,  -9.0990991 ,  -9.07907908,  -9.05905906,
        -9.03903904,  -9.01901902,  -8.998999  ,  -8.97897898,
        -8.95895896,  -8.93893894,  -8.91891892,  -8.8988989 ,
        -8.87887888,  -8.85885886,  -8.83883884,  -8.81881882,
        -8.7987988 ,  -8.77877878,  -8.75875876,  -8.73

In [3]:
import numpy as np

def relu(x):
    """Rectified Linear Unit"""
    return np.maximum(0, x)

def relu6(x):
    """ReLU6: ReLU с ограничением сверху значением 6"""
    return np.minimum(np.maximum(0, x), 6)

def softplus_naive(x, beta=1.0):
    """Наивная реализация SoftPlus (может вызывать проблемы!)"""
    return (1.0 / beta) * np.log(1.0 + np.exp(beta * x))

def softplus_stable(x, beta=1.0):
    """Стабильная реализация SoftPlus"""
    # Используем np.logaddexp для численной стабильности
    return (1.0 / beta) * np.logaddexp(0.0, beta * x)

In [4]:
# def SoftPlus(x):
#   return np.log(1+ np.exp(x))

In [5]:
def SoftPlus(x):
  return np.logaddexp(0.0,x)

In [6]:
SoftPlus(a)

array([4.53988992e-05, 4.63169238e-05, 4.72535116e-05, 4.82090380e-05,
       4.91838858e-05, 5.01784458e-05, 5.11931166e-05, 5.22283047e-05,
       5.32844251e-05, 5.43619009e-05, 5.54611640e-05, 5.65826548e-05,
       5.77268230e-05, 5.88941268e-05, 6.00850342e-05, 6.13000224e-05,
       6.25395783e-05, 6.38041985e-05, 6.50943900e-05, 6.64106698e-05,
       6.77535652e-05, 6.91236145e-05, 7.05213667e-05, 7.19473819e-05,
       7.34022315e-05, 7.48864986e-05, 7.64007779e-05, 7.79456762e-05,
       7.95218127e-05, 8.11298188e-05, 8.27703390e-05, 8.44440307e-05,
       8.61515645e-05, 8.78936246e-05, 8.96709091e-05, 9.14841301e-05,
       9.33340144e-05, 9.52213030e-05, 9.71467522e-05, 9.91111337e-05,
       1.01115234e-04, 1.03159857e-04, 1.05245822e-04, 1.07373964e-04,
       1.09545136e-04, 1.11760208e-04, 1.14020068e-04, 1.16325621e-04,
       1.18677791e-04, 1.21077520e-04, 1.23525770e-04, 1.26023521e-04,
       1.28571775e-04, 1.31171553e-04, 1.33823896e-04, 1.36529867e-04,
      

In [ ]:
import matplotlib.pyplot as plt

plt.plot(1 / beta * np.logaddexp(0.0, beta * a))

NameError: name 'beta' is not defined

In [ ]:
# Создаем тестовые данные
a = np.linspace(-10, 10, 1000)

# Применяем функции
relu_result = relu(a)
relu6_result = relu6(a)
softplus_result = softplus_stable(a, beta=1.0)

### Агрегирующие функции

In [ ]:
np.random.seed(777)
a = np.random.randint(0, 6, size=(8,))
a[3] = 10
a

array([ 3,  1,  5, 10,  1,  2,  0,  2])

In [ ]:
a.min(), a.max(), a.argmax(), a.sum(), a.prod(), a.mean()

(0, 10, 3, 24, 0, 3.0)

![vis-numpy-17.jpg](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/vis-numpy-17.jpg)

Агрегация возможна вдоль какого-то из измерений массива - параметр `axis`.
![vis-numpy-18.jpg](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/vis-numpy-18.jpg)

#### Задача 2

При работе с вероятностями часто бывает важно, чтобы они суммировались в 1. Как нормализовать массив чисел для получения соотвествующих вероятностей?

In [7]:
weights = np.array([4, 8, 10, 3, 1, 18])

In [8]:
prob = weights/np.sum(weights)
prob

array([0.09090909, 0.18181818, 0.22727273, 0.06818182, 0.02272727,
       0.40909091])

#### Задача 3

Реализуйте процедуру маргинализации таблицы совместного распределения по строкам. Получив маргинальное распределение, сделайте из исходной таблицы совместного распределения таблицу условных вероятностей по строкам при условии строк.

Пример:
```
[[0.1, 0.1, 0.2,          [0.4,         [[0.25, 0.25, 0.50,
  0.1, 0.0, 0.4,    -->    0.5,   -->     0.20, 0.00, 0.80,
  0.1, 0.0, 0.0]]          0.1]           1.00, 0.00, 0.00]]
```

Иллюстрация для усиления понимания:
![marginalization](https://data.bioml.ru/htdocs/courses/python/datasci/scipy/img/marginalization.png)

In [10]:
def margginalize_rows(joint_dist):
  return np.sum(joint_dist, axis =1)

In [9]:
def cond_prob(joint_dist):
  row_marg= margginalize_rows(joint_dist)
  row_marg_safe=np.where(row_marg == 1, 1e-10, row_marg)
  return joint_dist/row_marg_safe[:, np.newaxis]

In [ ]:
import numpy as np

def marginalize_rows(joint_dist):
    """
    Маргинализация по строкам (суммирование по столбцам)
    Возвращает маргинальное распределение по строкам
    """
    return np.sum(joint_dist, axis=1)

def conditional_probabilities_rows(joint_dist):
    """
    Условные вероятности по строкам P(столбец|строка)
    """
    # Получаем маргинальные вероятности строк
    row_marginals = marginalize_rows(joint_dist)

    # Для избежания деления на ноль
    # Добавляем маленькое значение к нулевым маргиналам
    row_marginals_safe = np.where(row_marginals == 0, 1e-10, row_marginals)

    # Деление каждого элемента на сумму его строки
    # keepdims=True сохраняет размерность для правильного деления
    return joint_dist / row_marginals_safe[:, np.newaxis]

In [11]:
np.random.seed(777)
a = np.random.randint(0, 8, (4, 6)).astype(np.float64)
a /= a.sum()
a

array([[0.07, 0.07, 0.03, 0.06, 0.07, 0.01],
       [0.07, 0.05, 0.07, 0.04, 0.07, 0.01],
       [0.06, 0.02, 0.  , 0.07, 0.02, 0.05],
       [0.06, 0.  , 0.03, 0.01, 0.02, 0.04]])

In [14]:
a/a.sum(axis=1, keepdims=True)

array([[0.22580645, 0.22580645, 0.09677419, 0.19354839, 0.22580645,
        0.03225806],
       [0.22580645, 0.16129032, 0.22580645, 0.12903226, 0.22580645,
        0.03225806],
       [0.27272727, 0.09090909, 0.        , 0.31818182, 0.09090909,
        0.22727273],
       [0.375     , 0.        , 0.1875    , 0.0625    , 0.125     ,
        0.25      ]])

### Операции индексации

![numpy_mem_layout](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy_mem_layout.png)

![classic_ind](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy_indexing.png)

#### Задача 4

Напишите функцию, создающую "шахматную доску" выбранного размера из нулей и единиц. В нижнем левом углу обязательно должна стоять единица при любом размере доски.

In [21]:
def generate_checkerboard(shape=(8, 8), dtype=np.int8):
  board = np.zeros((6,7),dtype=np.int64)
  board[-1::-2, ::2] = 1
  board[-2::-2, 1::2] =1
  raise NotImplementedError

In [20]:
board = np.zeros((6,7),dtype=np.int64)
board[-1::-2, ::2] = 1
board[-2::-2, 1::2] =1
board

array([[0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0, 1]])

In [15]:
np.zeros((3,4), dtype = np.int8)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [ ]:
generate_checkerboard()

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]], dtype=int8)

#### Задача 5

Дан массив NumPy. Перемешайте значения внутри третьего столбца.

In [23]:
arr = np.broadcast_to(np.arange(0, 6)[:, np.newaxis], (6, 8)).copy()
arr

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [24]:
third_column = arr[:, 2].copy()
np.random.shuffle(third_column)
arr[:, 2] = third_column
arr

array([[0, 0, 4, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 1, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [27]:
np.random.shuffle(arr[:,2])
arr

array([[0, 0, 2, 0, 0, 0, 0, 0],
       [1, 1, 5, 1, 1, 1, 1, 1],
       [2, 2, 1, 2, 2, 2, 2, 2],
       [3, 3, 0, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 3, 5, 5, 5, 5, 5]])

### Fancy индексация

![fancy_ind](https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/numpy_indexing_fancy.png)

#### Задача 6

Как можно получить квадратную матрицу (произвольного размера) с единицами по обеим диагоналям?

_Указание_: сгенерируйте единичную матрицу функцией `np.eye`. Как можно ее "развернуть"?

In [43]:
def double_eye(n):
    main_diag = np.eye(n, dtype=int)
    anti_diag = np.fliplr(main_diag)  # Отражаем слева направо

    return main_diag | anti_diag
    raise NotImplementedError

In [45]:
def double_eye2(n):
  eye = np.zeros((n,n), dtype = np.int64)
  eye[range(n), range(n)] = 1
  eye[range(n), range(n-1,-1,-1)] = 1
  return eye

In [46]:
double_eye2(7)

array([[1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1]])

In [44]:
double_eye(7)

array([[1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1]])

In [32]:
main_diag = np.eye(7, dtype=int)
main_diag

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [35]:
anti_diag = np.eye(7, dtype=int)[::-1]
anti_diag

array([[0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]])

In [38]:
a = main_diag | anti_diag
a

array([[1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1]])

In [ ]:
double_eye(5)

array([[1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 0, 0, 1]])

In [ ]:
double_eye(8)

array([[1, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 1]])

#### Задача 7

Напишите функцию, которая является аналогом функции `np.eye` и создает единичную матрицу выбранного размера.

*Бонус: создайте параметр, который позволит ей создавать отраженную единичную матрицу (т.е. с единицами по побочной диагонали).

In [ ]:
def i(size, inverted=False):
    raise NotImplementedError

#### Задача 8

Дан массив NumPy. Перемешайте все значения в 1, 2 и 4 столбцах между собой (без сохранения столбцов).

In [54]:
arr = np.broadcast_to(np.arange(0, 6), (8, 6)).copy()
arr

array([[0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5],
       [0, 1, 2, 3, 4, 5]])

In [62]:
x = arr[:,[1,2,4]].ravel()
np.random.shuffle(x)
arr[:,[1,2,4]] = x.reshape(-1,3)
arr

array([[0, 4, 2, 3, 4, 5],
       [0, 2, 1, 3, 1, 5],
       [0, 4, 1, 3, 1, 5],
       [0, 2, 4, 3, 1, 5],
       [0, 1, 2, 3, 2, 5],
       [0, 2, 4, 3, 2, 5],
       [0, 1, 4, 3, 4, 5],
       [0, 1, 4, 3, 2, 5]])

### Фильтрация и маски



In [ ]:
a = np.arange(20)
filter_array = a % 3 != 0
filter_array

array([False,  True,  True, False,  True,  True, False,  True,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
       False,  True])

In [ ]:
a[filter_array]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19])

<img src="https://data.bioml.ru/htdocs/courses/python/datasci/numpy/img/masking.png" width="500" />

#### Задача 9

Дан массив NumPy. Добавьте ко всем числам $\ge 8$ единицу.

In [ ]:
np.random.seed(777)
arr = np.random.randint(0, 10, (7, 9))
arr

array([[7, 6, 7, 1, 7, 4, 7, 9, 8],
       [7, 2, 0, 1, 2, 4, 5, 7, 1],
       [7, 2, 2, 7, 4, 8, 6, 2, 7],
       [8, 0, 8, 3, 2, 0, 3, 3, 4],
       [0, 6, 5, 7, 5, 5, 8, 1, 4],
       [7, 4, 4, 0, 9, 4, 5, 0, 5],
       [8, 0, 5, 7, 9, 6, 4, 7, 1]])

array([[ 7,  6,  7,  1,  7,  4,  7, 10,  9],
       [ 7,  2,  0,  1,  2,  4,  5,  7,  1],
       [ 7,  2,  2,  7,  4,  9,  6,  2,  7],
       [ 9,  0,  9,  3,  2,  0,  3,  3,  4],
       [ 0,  6,  5,  7,  5,  5,  9,  1,  4],
       [ 7,  4,  4,  0, 10,  4,  5,  0,  5],
       [ 9,  0,  5,  7, 10,  6,  4,  7,  1]])

#### Задача 10

Дан "высокий" 2D-массив NumPy. Отфильтруйте все строки, в которых есть отрицательные числа.

In [ ]:
np.random.seed(777)
arr = np.random.randint(-2, 10, (200, 4))
arr[:12]  # Preview top 12 rows

array([[ 5,  9,  4,  5],
       [-1,  5,  2,  5],
       [ 7,  8,  6,  5],
       [ 0, -2,  9, -1],
       [ 0,  2,  3,  5],
       [-1,  9,  5,  8],
       [ 0,  0,  5,  2],
       [ 6,  4,  0,  8],
       [ 5,  6, -2,  6],
       [ 1,  8,  0, -2],
       [ 1,  1,  2,  9],
       [-2,  4,  3,  5]])

### Комбинация изученного

#### Задача 11

Дан массив NumPy с пропущенными данными.

1. Отфильтруйте столбцы, содержащие два и более пропусков.
2. Затем заполните оставшиеся столбцы средним по таблице.

In [ ]:
np.random.seed(5)
arr = -np.log(np.random.uniform(-0.1, 0.9, (10, 7))).round(2)
arr

<ipython-input-153-11853aae09f3>:2: RuntimeWarning: invalid value encountered in log
  arr = -np.log(np.random.uniform(-0.1, 0.9, (10, 7))).round(2)


array([[2.1 , 0.26, 2.24, 0.2 , 0.95, 0.67, 0.41],
       [0.87, 1.63, 2.43,  nan, 0.45, 1.07, 2.84],
       [0.25, 1.75, 1.16, 1.63, 0.64, 0.73, 0.69],
       [1.8 , 1.69, 1.87, 1.48, 3.12, 2.72, 0.15],
       [0.15, 2.43,  nan, 2.26, 0.51, 0.39,  nan],
       [0.74,  nan, 0.88, 0.62, 0.12, 1.84, 0.35],
       [0.26, 0.2 ,  nan, 1.  , 0.13, 1.21, 0.34],
       [0.81, 0.4 , 0.95,  nan,  nan, 4.47, 1.89],
       [0.15, 0.63, 0.33, 0.76, 0.62, 0.34, 0.19],
       [0.21, 0.32,  nan, 1.34,  nan, 0.81, 0.36]])

#### Задача 12

При работе с биологическими объектами вычислительными методами вам часто придется осуществлять кодирование объектов.

Напишите функцию, которая превращает нуклеотидную последовательность ДНК (считайте, что она состоит только из букв A, T, G, C) в NumPy-массив размера $4 \times N$, где $N$ - длина последовательности.

_Подсказка_: Такой вид кодирования называется "one-hot encoding".

_Дополнительно_: подумайте о том, как можно быстро превратить закодированную последовательность в комплементарную и обратную комплементарную? Можно ли это сделать функцией `np.flip`? От чего это зависит?

In [ ]:
def encode_seq(s):
    raise NotImplementedError

#### Задача 13

Добавьте в закодированную one-hot белоккодирующую нуклеотидную последовательность канал, содержащий информацию о номере кодона.

Результирующий массив должен иметь размеры $5 \times N$.

In [ ]:
s = encode_seq("ATGCCCAAACGATAG")
s

array([[1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])